---
# tasks file for deploy

- name: Stop running Flask application
  systemd:
    name: photobank
    state: stopped
  ignore_errors: yes

- name: Remove application folder
  file:
    path: "{{ deploy_dir }}"
    state: absent
