---
# tasks file for deploy

- name: Stop running Flask application
  systemd:
    name: photobank
    state: stopped
  ignore_errors: yes

- name: Remove application folder
  file:
    path: "{{ app_dir }}"
    state: absent

- name: Git checkout
  git:
    repo="{{ git_repo }}"
    dest="{{ app_dir }}"
    version="{{ git_branch }}"
    accept_hostkey=yes
    force=yes
    key_file=/root/.ssh/id_rsa

- name: Change application`s config
  template: src=config.j2 dest="{{ app_dir }}/config.py"

- name: Use virtual env for python
  shell: pyenv local {{ project_name }}
  args:
    chdir: "{{ app_dir }}"

- name: Install python modules to virtual env
  shell: pip install -r requirements.txt
  args:
    chdir: "{{ app_dir }}"

