---
# tasks file for deploy

- name: Stop running Flask application
  systemd:
    name: photobank
    state: stopped
  ignore_errors: yes

- name: Remove application folder
  file:
    path: "{{ app_dir }}"
    state: absent

- name: Git checkout
  git:
    repo="{{ git_repo }}"
    dest="{{ app_dir }}"
    version="{{ git_branch }}"
    accept_hostkey=yes
    force=yes
    key_file=/root/.ssh/id_rsa
