---
# tasks file for deploy

- name: Stop running Flask application
  systemd:
    name: photobank
    state: stopped

- name: Remove application folder
  file:
    path: {{ deploy_dir }}
    state: absent
