---
# tasks file for deploy

- name: Stop running Flask application
  systemd:
    name: photobank
    state: stopped
  ignore_errors: yes

- name: Remove application folder
  file:
    path: "{{ deploy_dir }}"
    state: absent

- name: Copy key file
  copy:
    src: ~/.ssh/id_key.pub
    dest: /tmp/id_key.pub

- name: Git checkout
  git:
    repo: "{{ git_repo }}"
    dest: "{{ deploy_dir }}"
    version: "{{ git_branch }}"
    accept_hostkey=yes
    force=yes
    key_file: /tmp/id_key.pub
